SWEP.Base = "homigrad_base_shotgun"
SWEP.Spawnable = true
SWEP.AdminOnly = false
SWEP.PrintName = "Benelli M4 Super 90"
SWEP.Author = "Benelli Armi S.p.A."
SWEP.Instructions = "Semi-automatic shotgun chambered in 12/70"
SWEP.Category = "Weapons - Shotguns"
SWEP.Slot = 2
SWEP.SlotPos = 10
SWEP.ViewModel = ""
SWEP.WorldModel = "models/weapons/w_shot_xm1014.mdl"
SWEP.Spawnable = false
SWEP.WepSelectIcon2 = Material("pwb2/vgui/weapons/m4super90.png")
SWEP.IconOverride = "pwb2/vgui/weapons/m4super90.png"
SWEP.LeftFingerPose = {
	l_finger0 = Angle(10, -12, -25),
	l_finger02 = Angle(-10, 30, 0),
	l_finger1 = Angle(0, -10, 0),
	l_finger2 = Angle(0, -10, 0)
}
SWEP.ReloadSound = "weapons/tfa_ins2/m1014/toz_shell_insert_2.wav"
SWEP.Primary.SoundEmpty = {"zcitysnd/sound/weapons/toz_shotgun/handling/toz_empty.wav", 75, 100, 105, CHAN_WEAPON, 2}
SWEP.CustomShell = "12x70"
SWEP.ScrappersSlot = "Primary"
SWEP.weaponInvCategory = 1
SWEP.ShellEject = "ShotgunShellEject"
SWEP.Primary.ClipSize = 6
SWEP.Primary.DefaultClip = 6
SWEP.Primary.Automatic = false
SWEP.Primary.Ammo = "12/70 gauge"
SWEP.Primary.Cone = 0
SWEP.Primary.Damage = 16
SWEP.Primary.Spread = Vector(0.01, 0.01, 0.01)
SWEP.Primary.Force = 12
SWEP.Primary.Sound = {"toz_shotgun/toz_fp.wav", 80, 70, 75}
SWEP.Primary.Wait = 0.2
SWEP.NumBullet = 8
SWEP.DeploySnd = {"homigrad/weapons/draw_hmg.mp3", 55, 100, 110}
SWEP.HolsterSnd = {"homigrad/weapons/hmg_holster.mp3", 55, 100, 110}
SWEP.addSprayMul = 1
SWEP.weight = 4
SWEP.HoldType = "rpg"
SWEP.ReloadHold = "ar2"
SWEP.ZoomPos = Vector(-1.45, 0.36, 33)
SWEP.RHandPos = Vector(-5, -2, 0)
SWEP.LHandPos = Vector(7, -2, -2)
SWEP.SprayRand = {Angle(-0.2, -0.4, 0), Angle(-0.4, 0.4, 0)}
SWEP.Ergonomics = 0.9
SWEP.AnimShootMul = 2
SWEP.AnimShootHandMul = 10
SWEP.Penetration = 8
SWEP.ReloadTime = 1
SWEP.AnimInsert = 0.1
SWEP.AnimDraw = 0.4
SWEP.ReloadDrawTime = 0.1
SWEP.ReloadDrawCooldown = 0.1
SWEP.ReloadInsertTime = 0.1
SWEP.ReloadInsertCooldown = 0.25
SWEP.ReloadInsertCooldownFire = 0.1
SWEP.lengthSub = 20
SWEP.handsAng = Angle(-1, 1, 0)
SWEP.attPos = Vector(0, 0, -0.3)
SWEP.punchmul = 3
SWEP.punchspeed = 0.7
SWEP.ShockMultiplier = 3
SWEP.PPSMuzzleEffect = "pcf_jack_mf_mshotgun"
SWEP.LocalMuzzlePos = Vector(25.942, -0.202, 3.586)
SWEP.LocalMuzzleAng = Angle(0, -0.024, 90.248)
SWEP.WeaponEyeAngles = Angle(0, 0, 0)
SWEP.UseCustomWorldModel = true
SWEP.WorldPos = Vector(5, -1, 0)
SWEP.WorldAng = Angle(0, 0, 0)
SWEP.DistSound = "toz_shotgun/toz_dist.wav"
